#!/bin/bash

if [ -n "$1" ]; then
    branch_name="$1"
else
    echo "No branch name provided. Exiting."
    exit
fi

if git diff --quiet; then
    echo "No unstaged changes, proceeding to switch to main."
else
    echo "Unstaged changes found. Stashing them."
    git stash
    stashed=true
fi

git switch main
git pull

git checkout -b "$branch_name"
git push --set-upstream origin "$branch_name"

if [ "$stashed" = true ]; then
    echo "Unstashing changes."
    git stash pop
fi
