#!/bin/bash

if [ -n "$1" ]; then
    branch_name="$1"
else
    echo "No branch name provided. Exiting."
    exit  # Does this work?
fi

git stash

git switch main

git pull

git checkout -b "$branch_name"

git push --set-upstream origin "$branch_name"
